const countryList = {
  AED: ["Emirati Dirham", "AE"],
  AFN: ["Afghani", "AF"],
  XCD: ["East Caribbean Dollar", "AG"],
  ALL: ["Lek", "AL"],
  AMD: ["Armenian Dram", "AM"],
  ANG: ["Netherlands Antillean Guilder", "AN"],
  AOA: ["Kwanza", "AO"],
  AQD: ["Antarctic Dollar", "AQ"],
  ARS: ["Argentine Peso", "AR"],
  AUD: ["Australian Dollar", "AU"],
  AZN: ["Azerbaijan Manat", "AZ"],
  BAM: ["Bosnia-Herzegovina Convertible Mark", "BA"],
  BBD: ["Barbadian Dollar", "BB"],
  BDT: ["Taka", "BD"],
  XOF: ["CFA Franc BCEAO", "BE"],
  BGN: ["Bulgarian Lev", "BG"],
  BHD: ["Bahraini Dinar", "BH"],
  BIF: ["Burundi Franc", "BI"],
  BMD: ["Bermudian Dollar", "BM"],
  BND: ["Brunei Dollar", "BN"],
  BOB: ["Boliviano", "BO"],
  BRL: ["Brazilian Real", "BR"],
  BSD: ["Bahamian Dollar", "BS"],
  NOK: ["Norwegian Krone", "BV"],
  BWP: ["Pula", "BW"],
  BYR: ["Belarusian Ruble", "BY"],
  BZD: ["Belize Dollar", "BZ"],
  CAD: ["Canadian Dollar", "CA"],
  CDF: ["Congolese Franc", "CD"],
  XAF: ["CFA Franc BEAC", "CF"],
  CHF: ["Swiss Franc", "CH"],
  CLP: ["Chilean Peso", "CL"],
  CNY: ["Yuan Renminbi", "CN"],
  COP: ["Colombian Peso", "CO"],
  CRC: ["Costa Rican Colon", "CR"],
  CUP: ["Cuban Peso", "CU"],
  CVE: ["Cape Verdean Escudo", "CV"],
  CYP: ["Cypriot Pound", "CY"],
  CZK: ["Czech Koruna", "CZ"],
  DJF: ["Djiboutian Franc", "DJ"],
  DKK: ["Danish Krone", "DK"],
  DOP: ["Dominican Peso", "DO"],
  DZD: ["Algerian Dinar", "DZ"],
  ECS: ["Ecuadorian Sucre", "EC"],
  EEK: ["Estonian Kroon", "EE"],
  EGP: ["Egyptian Pound", "EG"],
  ETB: ["Ethiopian Birr", "ET"],
  EUR: ["Euro", "FR"],
  FJD: ["Fijian Dollar", "FJ"],
  FKP: ["Falkland Islands Pound", "FK"],
  GBP: ["British Pound", "GB"],
  GEL: ["Georgian Lari", "GE"],
  GGP: ["Guernsey Pound", "GG"],
  GHS: ["Ghanaian Cedi", "GH"],
  GIP: ["Gibraltar Pound", "GI"],
  GMD: ["Gambian Dalasi", "GM"],
  GNF: ["Guinean Franc", "GN"],
  GTQ: ["Guatemalan Quetzal", "GT"],
  GYD: ["Guyanese Dollar", "GY"],
  HKD: ["Hong Kong Dollar", "HK"],
  HNL: ["Honduran Lempira", "HN"],
  HRK: ["Croatian Kuna", "HR"],
  HTG: ["Haitian Gourde", "HT"],
  HUF: ["Hungarian Forint", "HU"],
  IDR: ["Indonesian Rupiah", "ID"],
  ILS: ["Israeli Shekel", "IL"],
  INR: ["Indian Rupee", "IN"],
  IQD: ["Iraqi Dinar", "IQ"],
  IRR: ["Iranian Rial", "IR"],
  ISK: ["Icelandic Krona", "IS"],
  JMD: ["Jamaican Dollar", "JM"],
  JOD: ["Jordanian Dinar", "JO"],
  JPY: ["Japanese Yen", "JP"],
  KES: ["Kenyan Shilling", "KE"],
  KGS: ["Kyrgyzstani Som", "KG"],
  KHR: ["Cambodian Riel", "KH"],
  KMF: ["Comorian Franc", "KM"],
  KPW: ["North Korean Won", "KP"],
  KRW: ["South Korean Won", "KR"],
  KWD: ["Kuwaiti Dinar", "KW"],
  KYD: ["Cayman Islands Dollar", "KY"],
  KZT: ["Kazakhstani Tenge", "KZ"],
  LAK: ["Lao Kip", "LA"],
  LBP: ["Lebanese Pound", "LB"],
  LKR: ["Sri Lankan Rupee", "LK"],
  LRD: ["Liberian Dollar", "LR"],
  LSL: ["Lesotho Loti", "LS"],
  LTL: ["Lithuanian Litas", "LT"],
  LVL: ["Latvian Lats", "LV"],
  LYD: ["Libyan Dinar", "LY"],
  MAD: ["Moroccan Dirham", "MA"],
  MDL: ["Moldovan Leu", "MD"],
  MGA: ["Malagasy Ariary", "MG"],
  MKD: ["Macedonian Denar", "MK"],
  MMK: ["Myanmar Kyat", "MM"],
  MNT: ["Mongolian Tugrik", "MN"],
  MOP: ["Macanese Pataca", "MO"],
  MRO: ["Mauritanian Ouguiya", "MR"],
  MTL: ["Maltese Lira", "MT"],
  MUR: ["Mauritian Rupee", "MU"],
  MVR: ["Maldivian Rufiyaa", "MV"],
  MWK: ["Malawian Kwacha", "MW"],
  MXN: ["Mexican Peso", "MX"],
  MYR: ["Malaysian Ringgit", "MY"],
  MZN: ["Mozambican Metical", "MZ"],
  NAD: ["Namibian Dollar", "NA"],
  XPF: ["CFP Franc", "NC"],
  NGN: ["Nigerian Naira", "NG"],
  NIO: ["Nicaraguan Cordoba", "NI"],
  NPR: ["Nepalese Rupee", "NP"],
  NZD: ["New Zealand Dollar", "NZ"],
  OMR: ["Omani Rial", "OM"],
  PAB: ["Panamanian Balboa", "PA"],
  PEN: ["Peruvian Nuevo Sol", "PE"],
  PGK: ["Papua New Guinean Kina", "PG"],
  PHP: ["Philippine Peso", "PH"],
  PKR: ["Pakistani Rupee", "PK"],
  PLN: ["Polish Zloty", "PL"],
  PYG: ["Paraguayan Guarani", "PY"],
  QAR: ["Qatari Riyal", "QA"],
  RON: ["Romanian Leu", "RO"],
  RSD: ["Serbian Dinar", "RS"],
  RUB: ["Russian Ruble", "RU"],
  RWF: ["Rwandan Franc", "RW"],
  SAR: ["Saudi Riyal", "SA"],
  SBD: ["Solomon Islands Dollar", "SB"],
  SCR: ["Seychellois Rupee", "SC"],
  SDG: ["Sudanese Pound", "SD"],
  SEK: ["Swedish Krona", "SE"],
  SGD: ["Singapore Dollar", "SG"],
  SKK: ["Slovak Koruna", "SK"],
  SLL: ["Sierra Leonean Leone", "SL"],
  SOS: ["Somali Shilling", "SO"],
  SRD: ["Surinamese Dollar", "SR"],
  STD: ["Sao Tome and Principe Dobra", "ST"],
  SVC: ["Salvadoran Colon", "SV"],
  SYP: ["Syrian Pound", "SY"],
  SZL: ["Swazi Lilangeni", "SZ"],
  THB: ["Thai Baht", "TH"],
  TJS: ["Tajikistani Somoni", "TJ"],
  TMT: ["Turkmenistani Manat", "TM"],
  TND: ["Tunisian Dinar", "TN"],
  TOP: ["Tongan Paanga", "TO"],
  TRY: ["Turkish Lira", "TR"],
  TTD: ["Trinidad and Tobago Dollar", "TT"],
  TWD: ["New Taiwan Dollar", "TW"],
  TZS: ["Tanzanian Shilling", "TZ"],
  UAH: ["Ukrainian Hryvnia", "UA"],
  UGX: ["Ugandan Shilling", "UG"],
  USD: ["United States Dollar", "US"],
  UYU: ["Uruguayan Peso", "UY"],
  UZS: ["Uzbekistani Som", "UZ"],
  VEF: ["Venezuelan Bolívar", "VE"],
  VND: ["Vietnamese Dong", "VN"],
  VUV: ["Vanuatu Vatu", "VU"],
  YER: ["Yemeni Rial", "YE"],
  ZAR: ["South African Rand", "ZA"],
  ZMK: ["Zambian Kwacha", "ZM"],
  ZWD: ["Zimbabwean Dollar", "ZW"],
};
